name: ❓: Test App before pushing
on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install requirements
        run: pip3 install -r app/requirements.txt

      - name: Test python code with Pytest
        run: pytest

      # - name: Calculate code coverage

      - name: Check PEP8 with flake8
        run: flake8